const vehiculos = [
    {marca:"Chevrolet", modelo:"Celta", img:'/assets/img/celta.png'},
    {marca:"Renault", modelo:"Clio", img:'/assets/img/clio.png'},
    {marca:"Renault", modelo:"Kwid", img:'/assets/img/kwid.png'},
    {marca:"Chevrolet", modelo:"Alige", img:'/assets/img/agile.png'},
    {marca:"Chevrolet", modelo:"Onix", img:'/assets/img/onix.png'},
    {marca:"Volkswagen", modelo:"Trend", img:'/assets/img/trend.png'},
    {marca:"Renault", modelo:"Stepway", img:'/assets/img/stepway.png'},
    {marca:"Chevrolet", modelo:"Classic", img:'/assets/img/classic.png'},
    {marca:"Renault", modelo:"Symbol", img:'/assets/img/symbol.png'},
    {marca:"Chevrolet", modelo:"Prisma", img:'/assets/img/prisma.png'},
    {marca:"Ford", modelo:"Focus", img:'/assets/img/focus.png'},
    {marca:"Chevrolet", modelo:"Cobalt", img:'/assets/img/cobalt.png'},
    {marca:"Renault", modelo:"Logan", img:'/assets/img/logan.png'},
    {marca:"Peugeot", modelo:"Patner", img:'/assets/img/patner.png'},
    {marca:"Renault", modelo:"Kangoo", img:'/assets/img/kangoo.png'},
    {marca:"Volkswagen", modelo:"Suran", img:'/assets/img/suran.png'},
    {marca:"Chevrolet", modelo:"Spin", img:'/assets/img/spin.png'},
    {marca:"Volkswagen", modelo:"Vento", img:'/assets/img/vento.png'},
    {marca:"Honda", modelo:"Crv", img:'/assets/img/crv.png'},
    {marca:"Hyundai", modelo:"H1", img:'/assets/img/h1.png'},
]